service: conference-service

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-central-1
  stage: dev

package:
  individually: false
  include:
    - "src/**"
  exclude:
    - "**"

functions:
  load-data:
    handler: src/handler.load
    name: ${self:service}-load-data
    events:
      - http:
          path: data
          method: get
